version: 2
jobs:
  build:
    docker:
    - image: circleci/python:3.7.3
      environment:
        PIPENV_VENV_IN_PROJECT: true
    steps:
    - checkout
    - run:
        command: sudo chown -R circleci:circleci /usr/local/bin
    - run:
        command: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
    - run:
        command: "python3 -m venv ./tasmanian_venv\nsource ./tasmanian_venv/bin/activate\npip install -r requirements.txt \nbash tasmanian/tests/basic_tests.sh\n#sudo pip install pipenv\n#pipenv install\n"
workflows:
  version: 2
  workflow:
    jobs:
    - build

# Original config.yml file:
# version: 2.1
# jobs:
#   build:
#     docker: 
#       - image: circleci/python:3.7.3  #node:4.8.2 # the primary container, where your job's commands are run
#         environment: # environment variables for primary container
#           PIPENV_VENV_IN_PROJECT: true
# 
#     steps:
#       - checkout # check out source code to working directory
#       - run: sudo chown -R circleci:circleci /usr/local/bin
#       - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
#       - run: 
#           command: |
#              python3 -m venv ./tasmanian_venv
#              source ./tasmanian_venv/bin/activate
#              pip install -r requirements.txt 
#              bash tasmanian/tests/basic_tests.sh
#              #sudo pip install pipenv
#              #pipenv install
# 
#       #- save_cache: # cache Python dependencies using checksum of Pipfile as the cache-key
#       #    key: deps9-{{ .Branch }}-{{ checksum \"Pipfile.lock\" }}
#       #    paths:
#       #      - \".venv\"
#       #      - \"/usr/local/bin\"
#       #      - \"/usr/local/lib/python3.6/site-packages\"
# 
#       #- run:
#       #    bash tasmanian/tests/basic_tests.sh # run test
