version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/python:3.7.3  #node:4.8.2 # the primary container, where your job's commands are run
        environment: # environment variables for primary container
          PIPENV_VENV_IN_PROJECT: true

    steps:
      - checkout # check out source code to working directory
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - run: 
          command: |
            sudo pip install pipenv
            pipenv install

      - save_cache: # cache Python dependencies using checksum of Pipfile as the cache-key
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"

      - run:
          bash tasmanian/tests/basic_tests.sh # run test
